In [1]:
import numpy as np

Multiplicación de Dos Matrices

In [2]:
a = np.array([[1, 0, 0], [5, 1, 0], [-2, 3, 1]])

b = np.array([[4, -2, 1], [0, 3, 7], [0, 0, 2]])

In [3]:
print(a)

[[ 1  0  0]
 [ 5  1  0]
 [-2  3  1]]


In [4]:
print(b)

[[ 4 -2  1]
 [ 0  3  7]
 [ 0  0  2]]


In [5]:
def Mul_Matrices(a, b):
    if a.shape[1] != b.shape[0]:
        return "Las matrices no pueden ser multiplicadas"
    else:
        c = np.zeros((a.shape[0], b.shape[1]))
        for i in range(a.shape[0]):
            for j in range(b.shape[1]):
                for k in range(a.shape[1]):
                    c[i, j] += a[i, k] * b[k, j]

        return c

In [6]:
print(Mul_Matrices(a, b))

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]
