In [34]:
import numpy as np

a) Matriz de Coeficientes y Vector Independiente

In [36]:
matriz = np.array([[0.2, 0.1, 1, 1, 0], [0.1, 4, -1, 1, -1], [1, -1, 60, 0, -2], [1, 1, 0, 8, 4], [0, -1, -2, 4, 700]])
print(matriz)

[[ 2.e-01  1.e-01  1.e+00  1.e+00  0.e+00]
 [ 1.e-01  4.e+00 -1.e+00  1.e+00 -1.e+00]
 [ 1.e+00 -1.e+00  6.e+01  0.e+00 -2.e+00]
 [ 1.e+00  1.e+00  0.e+00  8.e+00  4.e+00]
 [ 0.e+00 -1.e+00 -2.e+00  4.e+00  7.e+02]]


In [39]:
v_ind = np.array([[1], [2], [3], [4], [5]])
print(v_ind)

[[1]
 [2]
 [3]
 [4]
 [5]]


b) Algoritmo de Descenso Conjugado

In [40]:
def descenso_conjugado(A,b,x_k,epsilon=0.01):
  r_k=(A @ x_k)-b
  p_k=-r_k
  k=0
  while np.linalg.norm(r_k)>epsilon:
    alpha=-(((r_k.T) @ p_k))/(p_k.T @ (A@p_k))
    x_k=x_k + (alpha * p_k)
    r_k=(A @ x_k)-b
    beta=(r_k.T @ (A @ p_k))/(p_k.T @ (A@p_k))
    p_k=-r_k + (beta * p_k)
    k+=1
  return x_k,k

c) Solución del Sistema e Iteraciones

In [41]:
x_0=np.array([[1], [1], [1], [1], [5]])
print(descenso_conjugado(matriz,v_ind,x_0))

(array([[ 7.85971308],
       [ 0.42292641],
       [-0.07359224],
       [-0.54064302],
       [ 0.01062611]]), 5)
